# Enhanced PostgreSQL setup with automatic migrations
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres_db
    
    shm_size: 128mb
    
    volumes:
      - ../internal/db/migrations:/docker-entrypoint-initdb.d:ro
      
      # Add persistent storage the data survives container recreation
      # - postgres_data:/var/lib/postgresql/data
    
    environment:
      # More explicit database configuration
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verySecurePassword
      
      # Optional: These can help with debugging if needed
      # POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s 
    
    ports:
      - "5432:5432"

