# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ../internal/db/migrations:/migrations/
    environment:
      POSTGRES_PASSWORD: verySecurePassword
    # command: ["bash", "/migrations/migrate.sh"]
